export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};
import Footer from '@components/Footer';
import Header from '@components/Header';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="bg-[#F8F8F8]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
